#!/bin/bash

for f in $(find $(dirname ${BASH_SOURCE[0]})); do
    if [[ ${f} =~ .git.* ]]; then
        continue
    fi
    own=$(stat -c "%U:%G" ${f})
    if [[ ${own} != root:yaws ]]; then
        echo false ${f}
        exit 2
    fi
done
exit 0
